# Generated by Django 5.0.4 on 2024-04-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.ImageField(upload_to='qr_codes/'),
        ),
    ]
