# Generated by Django 5.0.4 on 2024-04-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_order_delete_qrcode_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
